#pragma once
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <ranges>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <SFML/Graphics.hpp>
#include <entt/entt.hpp>
#include <box2d/box2d.h>
#include <behaviortree_cpp/bt_factory.h>