#pragma once

// player.tsx
enum TILE_ID_PLAYER {
	TILE_ID_PLAYER_IDLE_DOWN = 0,
	TILE_ID_PLAYER_IDLE_UP = 16,
	TILE_ID_PLAYER_IDLE_RIGHT = 32,
	TILE_ID_PLAYER_PUSH_DOWN = 8,
	TILE_ID_PLAYER_PUSH_UP = 24,
	TILE_ID_PLAYER_PUSH_RIGHT = 40,
	TILE_ID_PLAYER_WALK_DOWN = 48,
	TILE_ID_PLAYER_WALK_UP = 52,
	TILE_ID_PLAYER_WALK_RIGHT = 64,
	TILE_ID_PLAYER_RUN_DOWN = 51,
	TILE_ID_PLAYER_RUN_UP = 55,
	TILE_ID_PLAYER_RUN_RIGHT = 70,
	TILE_ID_PLAYER_FOREHAND_STRIKE_DOWN = 132,
	TILE_ID_PLAYER_FOREHAND_STRIKE_UP = 148,
	TILE_ID_PLAYER_FOREHAND_STRIKE_RIGHT = 164,
	TILE_ID_PLAYER_BOW_SHOT_DOWN = 133,
	TILE_ID_PLAYER_BOW_SHOT_UP = 149,
	TILE_ID_PLAYER_BOW_SHOT_RIGHT = 165,
	TILE_ID_PLAYER_DYING_RIGHT_DOWN = 178,
	TILE_ID_PLAYER_DYING_RIGHT_UP = 181,
	TILE_ID_PLAYER_DEAD_RIGHT_DOWN = 180,
	TILE_ID_PLAYER_DEAD_RIGHT_UP = 183,
};

// items2.tsx
enum TILE_ID_ITEM {
	TILE_ID_ITEM_RUPEE = 40,
	TILE_ID_ITEM_POTION = 77,
	TILE_ID_ITEM_SPEAR = 96,
	TILE_ID_ITEM_BERRIES = 162,
};

// slime.tsx
enum TILE_ID_SLIME {
	TILE_ID_SLIME_WALK_DOWN = 0,
	TILE_ID_SLIME_WALK_RIGHT = 4,
	TILE_ID_SLIME_WALK_UP = 8,
	TILE_ID_SLIME_WALK_LEFT = 12,
};