#pragma once

/*
* player.tsx
*/

#define TILE_ID_PLAYER_IDLE_DOWN 0
#define TILE_ID_PLAYER_IDLE_UP 16
#define TILE_ID_PLAYER_IDLE_RIGHT 32
#define TILE_ID_PLAYER_PUSH_DOWN 8
#define TILE_ID_PLAYER_PUSH_UP 24
#define TILE_ID_PLAYER_PUSH_RIGHT 40
#define TILE_ID_PLAYER_WALK_DOWN 48
#define TILE_ID_PLAYER_WALK_UP 52
#define TILE_ID_PLAYER_WALK_RIGHT 64
#define TILE_ID_PLAYER_RUN_DOWN 51
#define TILE_ID_PLAYER_RUN_UP 55
#define TILE_ID_PLAYER_RUN_RIGHT 70
#define TILE_ID_PLAYER_FOREHAND_STRIKE_DOWN 132
#define TILE_ID_PLAYER_FOREHAND_STRIKE_UP 148
#define TILE_ID_PLAYER_FOREHAND_STRIKE_RIGHT 164
#define TILE_ID_PLAYER_BOW_SHOT_DOWN 133
#define TILE_ID_PLAYER_BOW_SHOT_UP 149
#define TILE_ID_PLAYER_BOW_SHOT_RIGHT 165
#define TILE_ID_PLAYER_DYING_RIGHT_DOWN 178
#define TILE_ID_PLAYER_DYING_RIGHT_UP 181
#define TILE_ID_PLAYER_DEAD_RIGHT_DOWN 180
#define TILE_ID_PLAYER_DEAD_RIGHT_UP 183

/*
* items1.tsx
*/

#define TILE_ID_ITEM_RUPEE 40
#define TILE_ID_ITEM_POTION 77
#define TILE_ID_ITEM_SPEAR 96

/*
* slime.tsx
*/

#define TILE_ID_SLIME_WALK_DOWN 0
#define TILE_ID_SLIME_WALK_RIGHT 4
#define TILE_ID_SLIME_WALK_UP 8
#define TILE_ID_SLIME_WALK_LEFT 12